sudo: required
services:
  - docker

before_install:
  - docker build -t giadat1599/docker-react-ci -f Dockerfile.dev .

scripts:
  - docker run -e CI=true giadat1599/docker-react-ci npm run test -- --coverage
